### ISSUE TITLE
Cannot save transformation as a new page

### ISSUE THREAD

**Issue by bcouston** [dapaas/datagraft#51]
Uploaded a file, created a new transformation, clicked on the "Transform data" button (highlighted in image), filled in the Title and Description fields, pressed "Create".

Every time I attempted this, the site got stuck in a loading loop and eventually errored out.

![screen shot 2015-09-04 at 16 50 36](https://cloud.githubusercontent.com/assets/9949074/9688184/85292fa4-5325-11e5-9b8f-420edc05ec36.png)

![screen shot 2015-09-04 at 16 55 56](https://cloud.githubusercontent.com/assets/9949074/9688259/ef892412-5325-11e5-9389-1f89f4aaa4b6.png)

![screen shot 2015-09-04 at 16 05 07](https://cloud.githubusercontent.com/assets/9949074/9688279/1404b0b8-5326-11e5-8e5f-7a61a38faa1a.png)

(BUG)

**Comment by fungiboletus** [comment]
Looking at the logs, Grafterizer fails to fill the newly created RDF repository. Probably because the repository is not ready.

In the current version, the application tries 6 times spaced by 2 seconds. I can still raise the number of attempts or make the system wait more and more longer between the attempts but I feel like it's not the right solution.

We use the `/catalog/distributions/repository` and not `/catalog/distributions/repository_async` so the repository should be ready when we fill it.

**Comment by fungiboletus** [comment]
I deployed a hotfix : the application tries 20 times and wait 2 times more between each tentative.
